title: Yigang Shen
url: "https://shenyigang.github.io"
baseurl: "/shenyigang.github.io"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/shenyigang"
footer_text: "Page design by yigang Shen"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/shenyigang.github.io"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"

